services:

  postgres:
    image: postgres:17
    container_name: codehire-database

    restart: unless-stopped

    environment:
      POSTGRES_DB: codehire
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: codehire-backend

    restart: unless-stopped

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/codehire
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend

    container_name: codehire-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:80"

volumes:
  postgres_data: