spring.application.name=codehire
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/codehire}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update

